name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
        with:
          cache-dependency-path: tmpl.typ
      - run: |
          brew install font-fontawesome font-noto-serif-cjk-sc font-noto-sans-cjk-sc font-ibm-plex-sans font-ibm-plex-serif font-ibm-plex-mono
      - run: |
          mkdir artifacts
          typst compile en.typ artifacts/en.pdf
          typst compile zh.typ artifacts/zh.pdf
          typst compile slide_zh.typ artifacts/slide_zh.pdf
      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: artifacts
          destination-dir: cv
